### ISSUE TITLE
Plotly is missing from setup.py

### ISSUE THREAD

**Issue by cnx-tcsikos** [morganstanley/testplan#676]
After a fresh install using `pip install https://github.com/morganstanley/testplan/archive/latest.zip` on Windows results in successful install, however testplan fails to run due to missing dependency on `plotly`.
```
$ py test_plan.py
c:\users\...\appdata\local\programs\python\python37\lib\site-packages\testplan\exporters\testing\pdf\__init__.py:51: UserWarning: reportlab must be supported: No module named 'plotly'
  warnings.warn("reportlab must be supported: {}".format(exc))
Traceback (most recent call last):
  File "c:\users\...\appdata\local\programs\python\python37\lib\site-packages\testplan\exporters\testing\pdf\__init__.py", line 42, in <module>
    from . import renderers
  File "c:\users\...\appdata\local\programs\python\python37\lib\site-packages\testplan\exporters\testing\pdf\renderers\__init__.py", line 2, in <module>
    from .entries import registry as serialized_entry_registry
  File "c:\users\...\appdata\local\programs\python\python37\lib\site-packages\testplan\exporters\testing\pdf\renderers\entries\__init__.py", line 2, in <module>
    from .assertions import *
  File "c:\users\...\appdata\local\programs\python\python37\lib\site-packages\testplan\exporters\testing\pdf\renderers\entries\assertions.py", line 19, in <module>
    from testplan.testing.multitest.entries import assertions
  File "c:\users\...\appdata\local\programs\python\python37\lib\site-packages\testplan\testing\multitest\__init__.py", line 3, in <module>
    from .base import MultiTest
  File "c:\users\...\appdata\local\programs\python\python37\lib\site-packages\testplan\testing\multitest\base.py", line 22, in <module>
    from testplan.testing import base as testing_base
  File "c:\users\...\appdata\local\programs\python\python37\lib\site-packages\testplan\testing\base.py", line 34, in <module>
    from testplan.testing.multitest.entries.assertions import RawAssertion
  File "c:\users\...\appdata\local\programs\python\python37\lib\site-packages\testplan\testing\multitest\entries\assertions.py", line 23, in <module>
    from .base import BaseEntry
  File "c:\users\...\appdata\local\programs\python\python37\lib\site-packages\testplan\testing\multitest\entries\base.py", line 11, in <module>
    import plotly.io
ModuleNotFoundError: No module named 'plotly'
Traceback (most recent call last):
  File "test_plan.py", line 6, in <module>
    from testplan import test_plan
  File "c:\users\...\appdata\local\programs\python\python37\lib\site-packages\testplan\__init__.py", line 20, in <module>
    from testplan.base import (
  File "c:\users\...\appdata\local\programs\python\python37\lib\site-packages\testplan\base.py", line 6, in <module>
    from testplan.runnable import TestRunnerConfig, TestRunnerResult, TestRunner
  File "c:\users\...\appdata\local\programs\python\python37\lib\site-packages\testplan\runnable\__init__.py", line 1, in <module>
    from testplan.runnable.base import (
  File "c:\users\...\appdata\local\programs\python\python37\lib\site-packages\testplan\runnable\base.py", line 34, in <module>
    from testplan.runnable.interactive import TestRunnerIHandler
  File "c:\users\...\appdata\local\programs\python\python37\lib\site-packages\testplan\runnable\interactive\__init__.py", line 1, in <module>
    from .base import TestRunnerIHandler
  File "c:\users\...\appdata\local\programs\python\python37\lib\site-packages\testplan\runnable\interactive\base.py", line 16, in <module>
    from testplan.runnable.interactive import http
  File "c:\users\...\appdata\local\programs\python\python37\lib\site-packages\testplan\runnable\interactive\http.py", line 30, in <module>
    from .reloader import ModuleReloader
  File "c:\users\...\appdata\local\programs\python\python37\lib\site-packages\testplan\runnable\interactive\reloader.py", line 15, in <module>
    from testplan.testing.multitest import suite, MultiTest
  File "c:\users\...\appdata\local\programs\python\python37\lib\site-packages\testplan\testing\multitest\__init__.py", line 3, in <module>
    from .base import MultiTest
  File "c:\users\...\appdata\local\programs\python\python37\lib\site-packages\testplan\testing\multitest\base.py", line 22, in <module>
    from testplan.testing import base as testing_base
  File "c:\users\...\appdata\local\programs\python\python37\lib\site-packages\testplan\testing\base.py", line 34, in <module>
    from testplan.testing.multitest.entries.assertions import RawAssertion
  File "c:\users\...\appdata\local\programs\python\python37\lib\site-packages\testplan\testing\multitest\entries\assertions.py", line 23, in <module>
    from .base import BaseEntry
  File "c:\users\...\appdata\local\programs\python\python37\lib\site-packages\testplan\testing\multitest\entries\base.py", line 11, in <module>
    import plotly.io
ModuleNotFoundError: No module named 'plotly'
```
I presume it doesn't utilize the requirements.txt, only the setup.py, which is missing the plotly dependency.
After installing plotly, tests works again.

**Comment by yuxuan-ms** [comment]
@cnx-tcsikos Thanks for the feedback!  We've created #677 to fix it.
